config/routes.rb
Rails.application.routes.draw do
  resources :paired_deposits
  resources :deposits
  resources :taken_meals
  resources :meals
  resources :users

  root 'index#index'

  post 'index/meals' => 'index#meals'
  post 'index/deposits' => 'index#deposits'
  post 'index/assignMeal' => 'index#assign_meal'
  post 'index/unassignMeal' => 'index#unassign_meal'
  post 'index/assignDeposit' => 'index#assign_deposit'
  post 'index/unassignDeposit' => 'index#unassign_deposit'

  post 'import/update' => 'import#update'
  post 'import/test' => 'import#test'
  post 'import/deleteDB' => 'import#deleteDB'
  get 'import/index' => 'import#index'

end

app/models/paired_deposit.rb
class PairedDeposit < ActiveRecord::Base
  belongs_to :user
  belongs_to :deposit
end

app/controllers/paired_deposits_controller.rb
class PairedDepositsController < ApplicationController
  before_action :set_paired_deposit, only: [:show, :edit, :update, :destroy]

  # GET /paired_deposits
  # GET /paired_deposits.json
  def index
    @paired_deposits = PairedDeposit.all
  end

  # GET /paired_deposits/1
  # GET /paired_deposits/1.json
  def show
  end

  # GET /paired_deposits/new
  def new
    @paired_deposit = PairedDeposit.new
  end

  # GET /paired_deposits/1/edit
  def edit
  end

  # POST /paired_deposits
  # POST /paired_deposits.json
  def create
    @paired_deposit = PairedDeposit.new(paired_deposit_params)

    respond_to do |format|
      if @paired_deposit.save
        format.html { redirect_to @paired_deposit, notice: 'Paired deposit was successfully created.' }
        format.json { render :show, status: :created, location: @paired_deposit }
      else
        format.html { render :new }
        format.json { render json: @paired_deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /paired_deposits/1
  # PATCH/PUT /paired_deposits/1.json
  def update
    respond_to do |format|
      if @paired_deposit.update(paired_deposit_params)
        format.html { redirect_to @paired_deposit, notice: 'Paired deposit was successfully updated.' }
        format.json { render :show, status: :ok, location: @paired_deposit }
      else
        format.html { render :edit }
        format.json { render json: @paired_deposit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paired_deposits/1
  # DELETE /paired_deposits/1.json
  def destroy
    @paired_deposit.destroy
    respond_to do |format|
      format.html { redirect_to paired_deposits_url, notice: 'Paired deposit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_paired_deposit
      @paired_deposit = PairedDeposit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def paired_deposit_params
      params.require(:paired_deposit).permit(:date, :user_id, :deposit_id)
    end
end

app/helpers/paired_deposits_helper.rb
module PairedDepositsHelper
end

app/views/paired_deposits/_form.html.erb
<%= form_for(@paired_deposit) do |f| %>
  <% if @paired_deposit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@paired_deposit.errors.count, "error") %> prohibited this paired_deposit from being saved:</h2>

      <ul>
      <% @paired_deposit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :deposit_id %><br>
    <%= f.text_field :deposit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/paired_deposits/edit.html.erb
<h1>Editing Paired Deposit</h1>

<%= render 'form' %>

<%= link_to 'Show', @paired_deposit %> |
<%= link_to 'Back', paired_deposits_path %>

app/views/paired_deposits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Paired Deposits</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>User</th>
      <th>Deposit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @paired_deposits.each do |paired_deposit| %>
      <tr>
        <td><%= paired_deposit.date %></td>
        <td><%= paired_deposit.user %></td>
        <td><%= paired_deposit.deposit %></td>
        <td><%= link_to 'Show', paired_deposit %></td>
        <td><%= link_to 'Edit', edit_paired_deposit_path(paired_deposit) %></td>
        <td><%= link_to 'Destroy', paired_deposit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Paired deposit', new_paired_deposit_path %>

app/views/paired_deposits/new.html.erb
<h1>New Paired Deposit</h1>

<%= render 'form' %>

<%= link_to 'Back', paired_deposits_path %>

app/views/paired_deposits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @paired_deposit.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @paired_deposit.user %>
</p>

<p>
  <strong>Deposit:</strong>
  <%= @paired_deposit.deposit %>
</p>

<%= link_to 'Edit', edit_paired_deposit_path(@paired_deposit) %> |
<%= link_to 'Back', paired_deposits_path %>