config/routes.rb
Rails.application.routes.draw do
  resources :paired_deposits
  resources :deposits
  resources :taken_meals
  resources :meals
  resources :users

  root 'index#index'

  post 'index/meals' => 'index#meals'
  post 'index/deposits' => 'index#deposits'
  post 'index/assignMeal' => 'index#assign_meal'
  post 'index/unassignMeal' => 'index#unassign_meal'
  post 'index/assignDeposit' => 'index#assign_deposit'
  post 'index/unassignDeposit' => 'index#unassign_deposit'

  post 'import/update' => 'import#update'
  post 'import/test' => 'import#test'
  post 'import/deleteDB' => 'import#deleteDB'
  get 'import/index' => 'import#index'

end

app/models/taken_meal.rb
class TakenMeal < ActiveRecord::Base
  belongs_to :user
  belongs_to :meal
end

app/controllers/taken_meals_controller.rb
class TakenMealsController < ApplicationController
  before_action :set_taken_meal, only: [:show, :edit, :update, :destroy]

  # GET /taken_meals
  # GET /taken_meals.json
  def index
    render "index", :locals => {:taken_meals => TakenMeal.all, :paired_deposits => PairedDeposit.all}
  end

  # GET /taken_meals/1
  # GET /taken_meals/1.json
  def show
  end

  # GET /taken_meals/new
  def new
    @taken_meal = TakenMeal.new
  end

  # GET /taken_meals/1/edit
  def edit
  end

  # POST /taken_meals
  # POST /taken_meals.json
  def create
    @taken_meal = TakenMeal.new(taken_meal_params)

    respond_to do |format|
      if @taken_meal.save
        format.html { redirect_to @taken_meal, notice: 'Taken meal was successfully created.' }
        format.json { render :show, status: :created, location: @taken_meal }
      else
        format.html { render :new }
        format.json { render json: @taken_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /taken_meals/1
  # PATCH/PUT /taken_meals/1.json
  def update
    respond_to do |format|
      if @taken_meal.update(taken_meal_params)
        format.html { redirect_to @taken_meal, notice: 'Taken meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @taken_meal }
      else
        format.html { render :edit }
        format.json { render json: @taken_meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /taken_meals/1
  # DELETE /taken_meals/1.json
  def destroy
    @taken_meal.destroy
    respond_to do |format|
      format.html { redirect_to taken_meals_url, notice: 'Taken meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_taken_meal
      @taken_meal = TakenMeal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def taken_meal_params
      params.require(:taken_meal).permit(:date, :user_id, :meal_id)
    end
end

app/helpers/taken_meals_helper.rb
module TakenMealsHelper
end

app/views/taken_meals/_form.html.erb
<%= form_for(@taken_meal) do |f| %>
  <% if @taken_meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@taken_meal.errors.count, "error") %> prohibited this taken_meal from being saved:</h2>

      <ul>
      <% @taken_meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :meal_id %><br>
    <%= f.text_field :meal_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/taken_meals/edit.html.erb
<h1>Editing Taken Meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @taken_meal %> |
<%= link_to 'Back', taken_meals_path %>

app/views/taken_meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Připsaná jídla</h1>

<table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Meal</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% taken_meals.each do |taken_meal| %>
      <tr>
        <td><%= taken_meal.user.firstname %> <%= taken_meal.user.surname %></td>
        <td><%= taken_meal.meal.name %></td>
        <td><%= link_to 'Odstranit', taken_meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <h1>Připsané vklady</h1>

  <table class="table">
    <thead>
    <tr>
      <th>User</th>
      <th>Deposit</th>
      <th></th>
    </tr>
    </thead>

    <tbody>
    <% paired_deposits.each do |paired_deposit| %>
        <tr>
          <td><%= paired_deposit.user.firstname %> <%= paired_deposit.user.surname %></td>
          <td><%= paired_deposit.deposit.amount %></td>
          <td><%= link_to 'Odstranit', paired_deposit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
    <% end %>
    </tbody>

</table>

app/views/taken_meals/new.html.erb
<h1>New Taken Meal</h1>

<%= render 'form' %>

<%= link_to 'Back', taken_meals_path %>

app/views/taken_meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @taken_meal.date %>
</p>

<p>
  <strong>User:</strong>
  <%= @taken_meal.user %>
</p>

<p>
  <strong>Meal:</strong>
  <%= @taken_meal.meal %>
</p>

<%= link_to 'Edit', edit_taken_meal_path(@taken_meal) %> |
<%= link_to 'Back', taken_meals_path %>